### ISSUE TITLE
NOvA e20 build fails due to issue in MessageFacility v2_08_04

### ISSUE THREAD

**Issue by vhewes** [art-framework-suite/messagefacility#8]
**Describe the bug**
Work to migrate the NOvA ecosystem to `e20` is currently being held up by a CMake issue in MessageFacility v2_08_04: 
```CMake Error at /cvmfs/nova.opensciencegrid.org/externals/messagefacility/v2_08_04/slf7.x86_64.e20.debug/lib/messagefacility/cmake/messagefacilityConfig.cmake:182 (add_library):
  add_library cannot create ALIAS target "messagefacility::MF_catch_mainS"
  because target "messagefacility::MF_catch_main" is imported but not
  globally visible.
Call Stack (most recent call first):
  /cvmfs/nova.opensciencegrid.org/externals/cetbuildtools/v7_17_01/Modules/FindUpsPackage.cmake:38 (find_package)
  /cvmfs/nova.opensciencegrid.org/externals/cetbuildtools/v7_17_01/Modules/FindUpsPackage.cmake:157 (_use_find_package)
  CMakeLists.txt:53 (find_ups_product)
```

From looking through the commit history, I see that there were a few changes in the corresponding `CMakeLists.txt` (most recently [here](https://github.com/art-framework-suite/messagefacility/commit/2831da55224562c5781e236e7dbb3d7d2ad1d55a)) since `v2_06_01`, which is the version our current `e19` build uses. We're not sure exactly what the issue is, but it's either some quirk of the backwards compatibility mechanism that's causing an error in our ecosystem, or there's some new dependency we need to be introducing that's currently missing in our ecosystem. I tried introducing `catch` as a dependency, but that didn't seem to help at all.

It's entirely possible this isn't actually an error in MessageFacility itself, but either way, a few minutes of your time (especially @chissg) would really help us track this down. We've been stuck in a holding pattern on this issue for a while now, and it's easier for everybody in the long run if NOvA isn't stuck in an antiquated software stack.

**To Reproduce**
Hopefully you can provide some insight without needing to reproduce the issue yourself, but if you'd like to, you can do the following on the NOvA VMs:
```
cd <your working area>
cp -r /nova/app/users/fgao/NovaDAQ/ups_build_e20 .
cd ups_build_e20/build_novadaq
source /cvmfs/nova.opensciencegrid.org/externals/setup
setup ninja
source ../novadaq_v18/ups/setup_for_development -d
export CSTXSD_VERSION=v4_0_0j
buildtool -p --generator ninja
```

**If this is a high-priority issue**
I don't think I'm able to edit labels on the issue, but this is a problem that's been plaguing us for a while, and it would be really useful to get just a few minutes of your time to help track it down. Thank you!! -v

**Comment by knoepfel** [comment]
@vhewes, that version of `messagefacility` was built with `cetmodules` 2 and requires you to either build with `cetmodules` 2 or `cetbuildtools` version 8 (or higher).  If you make the following changes in your `product_deps` file, you should not have any troubles:

```diff
knoepfel@novagpvm01 ups $ diff -Nu /nova/app/users/fgao/NovaDAQ/ups_build_e20/novadaq_v18/ups/product_deps product_deps 
--- .../ups/product_deps	2022-03-29 12:27:47.113187290 -0500
+++ .../ups/product_deps	2022-05-13 12:32:21.765802742 -0500
@@ -25,7 +25,7 @@
 libwda          v2_30_0
 postgresql      v13_2
 
-cetbuildtools   v7_17_01  - only_for_build  
+cetbuildtools   v8_19_02  - only_for_build
 end_product_list
 
 
@@ -35,7 +35,7 @@
 e20:debug  e20:debug       e20        -nq-    -nq-    p392
 e20:prof   e20:prof        e20        -nq-    -nq-    p392
 e20:opt    e20:opt         e20        -nq-    -nq-    p392
-#end_qualifier_list
+end_qualifier_list
 
 table_fragment_begin
     # necessary environmental variables
```

Note that you will see a lot of deprecation warnings as `cetmodules`/`cetbuildtools` 8 will identify potentially problematic issues.  However, you do not need to resolve these to be able to use this version of `messsagefacility`.

Let us know if you have any troubles/questions.

**Comment by vhewes** [comment]
Perfect, thanks Kyle! I can confirm this fixes the messagefacility error on our end. I really appreciate the quick response, I don't think we would have figured this out on our own. As you said, this introduces a laundry list of new warnings, but those have nothing to do with MF and we can iron those out on our end. Closing this issue out now – thank you again!! -v

**Comment by knoepfel** [comment]
Glad it worked for you, @vhewes.
